# Generated by Django 3.2 on 2021-09-21 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.IntegerField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('safe_deal', models.BooleanField()),
                ('without_executor', models.BooleanField()),
                ('published', models.DateTimeField()),
                ('url', models.URLField()),
                ('chapters', models.ManyToManyField(to='backend.Chapter')),
            ],
        ),
    ]
