# Generated by Django 3.2 on 2021-09-21 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210921_1228'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='botuser',
            managers=[
                ('users', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='chapter',
            managers=[
                ('chapters', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='safe_deal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='without_executor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='TaskManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('New project', 'New Project')], max_length=30)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('done', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.project')),
            ],
            options={
                'ordering': ['-when'],
            },
            managers=[
                ('tasks', django.db.models.manager.Manager()),
            ],
        ),
    ]
