# Generated by Django 3.2 on 2021-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210921_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
