# Generated by Django 3.2 on 2021-09-21 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_botuser_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuser',
            old_name='bot_state',
            new_name='state',
        ),
    ]
