# Generated by Django 3.2 on 2021-09-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_rename_bot_state_botuser_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botuser',
            name='active',
        ),
        migrations.AddField(
            model_name='botuserfilter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
