# Generated by Django 3.2 on 2021-09-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20210921_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='botuserfilter',
            old_name='only_safe_deal',
            new_name='safe_deal',
        ),
        migrations.RenameField(
            model_name='botuserfilter',
            old_name='only_without_executor',
            new_name='without_executor',
        ),
    ]
