# Generated by Django 3.2 on 2021-09-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210921_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuserfilter',
            name='keywords',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
