# Generated by Django 3.2 on 2021-09-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_botuserfilter_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='botuser',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'Edit Budget Min'), (2, 'Edit Budget Max'), (3, 'Edit Keywords')], null=True),
        ),
    ]
